Feat/e rosita processing prep
DavidT3/DAXA pull request #154
Opened 2023-04-12 14:20 UTC by jessicapilling

2023-04-12 15:35 UTC, DavidT3 requested changes
A few tiny comments, won't take a second!

2023-04-12 15:35 UTC, DavidT3 commented on daxa/process/erosita/__init__.py
It would be good if you could get this message setup on your VSCode install:

\#  This code is a part of the Democratising Archival X-ray Astronomy (DAXA) module.
\#  Last modified by David J Turner (turne540@msu.edu) 23/11/2022, 16:42. Copyright (c) The Contributors

PyCharm just automatically puts it in for me, and updates the 'last updated' message when I commit - there must be something equivalent in VSCode. Not a priority though compared to actual dev work, just thought I'd put it here

2023-04-20 15:09 UTC, jessicapilling commented on daxa/process/_backend_check.py
> +    # Performing eSASS installation checks for eSASS outside of Docker
tested on apollo, and it returns the correct value for the apollo setup!

2023-04-20 15:24 UTC, DavidT3 approved these changes

2023-05-02 11:47 UTC, merged